"use strict"

const gMemes = [
  { id: 1, tags: ["crying","animal","cat"] },
  { id: 2, tags: ["animal","happy"] },
  { id: 3, tags: ["animal","baby","dog"] },
  { id: 4, tags: ["cat","sleep"] },
  { id: 5, tags: ["baby","happy","excited"] },
  { id: 6, tags: ["excited"] },
  { id: 7, tags: ["baby","surprised","funny"] },
  { id: 8, tags: ["funny","celebrity","happy"] },
  { id: 9, tags: ["celebrity","happy"] },
  { id: 10, tags: ["crying","animal","dog"] },
  { id: 11, tags: ["happy","animal","dog","excited","funny","laughing"] },
  { id: 12, tags: ["angry","animal"] },
  { id: 13, tags: ["funny","laughing"] },
  { id: 14, tags: ["laughing","celebrity"] },
  { id: 15, tags: ["crying"] },
  { id: 16, tags: ["crying","celebrity"] },
  { id: 17, tags: ["crying","animal","cat"] },
  { id: 18, tags: ["surprised","excited","celebrity","happy"] },
  { id: 19, tags: ["surprised","celebrity"] },
  { id: 20, tags: ["excited","celebrity"] },
  { id: 21, tags: ["crying"] },
  { id: 22, tags: ["angry"] },
  { id: 23, tags: ["crying","celebrity"] },
  { id: 24, tags: ["crying","happy","celebrity"] },
  { id: 25, tags: ["awkward","funny"] },
  { id: 26, tags: ["awkward"] },
  { id: 27, tags: ["surprised"] },
  { id: 28, tags: ["surprised"] },
  { id: 29, tags: ["surprised","animal"] },
  { id: 30, tags: ["surprised","animal","cat"] },
  { id: 31, tags: ["sleep","celebrity"] },
  { id: 32, tags: ["sleep"] },

];